---
title: "is_connected"
author: "Team 6"
date: "11/5/2014"
output: html_document
---
Function - is_connected
Input - g, a graph object; v1, a vertex label in g; v2, a vertex label in g.
Output - true if there is a path from v1 to v2 in g, false if not.
Description - Determine if there is any path between vertex v1 and vertex v2 in graph g. If v1 or v2 are not in g then throw an error.




```{r}

v1=1
v2=3
is_connected = function(g, v1, v2){
input=g4
n=length(input)
obj1<-input[[v1]]$edges
#degree 1
if (v2==obj1) {
    print(TRUE)
  }
  else{
    #degree 2
    obj2<-input[[obj1]]$edges
    if(v2==obj2){
      print(TRUE)
    }
    
    else{
      #degree3
       obj3<-input[[obj2]]$edges
       if(v2==obj3){
         print(TRUE)
       }
      
        else{
      #degree 4
       obj4<-input[[obj3]]$edges
       if(v2==obj4){
         print(TRUE)
       }
       
        else{
      #degree5
       obj4<-input[[obj3]]$edges
       if(v2==obj4){
         print(TRUE)
       }
      
        else{
      #degree6
       obj5<-input[[obj4]]$edges
       if(v2==obj5){
         print(TRUE)
       }
      
       else{
         print(FALSE)
       }
       
       print(FALSE)
       }
       
       print(FALSE)
       }
    print(FALSE)   
    }
    
  print(FALSE)  
  }

  print(FALSE)
}
  
}

```

If you want to test individual objects

```{r}

  g1 = list(A = list(edges   = c(1L),
                     weights = c(1)))

  g2 = list(A = list(edges   = c(1L, 2L),
                     weights = c(1, 1)),
            B = list(edges   = c(1L, 2L),
                     weights = c(1, 1)))

  g3 = list(A = list(edges   = c(1L, 2L),
                     weights = c(1, 1)),
            B = list(edges   = c(1L, 3L),
                     weights = c(1, 1)),
            C = list(edges   = c(2L, 3L),
                     weights = c(1, 1)))
  
  g4 = list(A = list(edges   = c(2L),
                     weights = c(1)),
            B = list(edges   = c(3L),
                     weights = c(1)),
            C = list(edges   = c(4L),
                     weights = c(1)),
            D = list(edges   = c(5L),
                     weights = c(1)),
            E = list(edges   = c(6L),
                     weights = c(1)),
            F = list(edges   = integer(),
                     weights = numeric()))


is_connected(g1,1,1) #false
is_connected(g2,1,1) #false
is_connected(g2,1,2)
is_connected(g2,2,1)
is_connected(g2,2,2) #false

is_connected(g3,1,1) #false
is_connected(g3,1,2)
is_connected(g3,2,1)
is_connected(g3,2,3)
is_connected(g3,3,2)
is_connected(g3,3,3) #false


is_connected(g4,1,2) 
is_connected(g4,1,3)  #false
is_connected(g4,1,4)  #false
is_connected(g4,1,5)  #false
is_connected(g4,1,6)   # Error in if (v2 == input[[v1]]$edges | v1 == input[[v2]]$edges) { :   argument is of length zero

is_connected(g4,6,1) # same error
is_connected(g4,6,2) # ''
is_connected(g4,6,3) # ''
is_connected(g4,6,4)  #''
is_connected(g4,6,5)#''


### Unconnected graphs

 g1 = list(A = list(edges   = integer(),
                     weights = numeric()))

  g2 = list(A = list(edges   = c(1L),
                     weights = c(1)),
            B = list(edges   = c(2L),
                     weights = c(1)))

  g3 = list(A = list(edges   = c(1L),
                     weights = c(1)),
            B = list(edges   = c(1L, 3L),
                     weights = c(1, 1)),
            C = list(edges   = c(3L),
                     weights = c(1)))


  expect_false(is_connected(g1,1,1))

  expect_true(is_connected(g2,1,1))
  expect_false(is_connected(g2,1,2))
  expect_false(is_connected(g2,2,1))
  expect_true(is_connected(g2,2,2))

  expect_true(is_connected(g3,1,1))
  expect_false(is_connected(g3,1,2))
  expect_true(is_connected(g3,2,1))
  expect_false(is_connected(g3,2,2))
  expect_true(is_connected(g3,2,3))
  expect_false(is_connected(g3,3,2))
  expect_true(is_connected(g3,3,3))


## Vertex error

  g1 = list(A = list(edges   = c(1L),
                     weights = c(1)))

  g2 = list(A = list(edges   = c(1L, 2L),
                     weights = c(1, 1)),
            B = list(edges   = c(1L, 2L),
                     weights = c(1, 1)))

  # Good labels

  expect_true(is_connected(g1,1,1))
  expect_true(is_connected(g1,"A","A"))
  expect_true(is_connected(g1,"A",1))
  expect_true(is_connected(g1,1,"A"))

  expect_true(is_connected(g2,1,2))
  expect_true(is_connected(g2,"A","B"))
  expect_true(is_connected(g2,"A",2))
  expect_true(is_connected(g2,1,"B"))

  expect_true(is_connected(g1,1,1L))
  expect_true(is_connected(g1,1L,1))
  expect_true(is_connected(g1,1L,1L))

  # Bad labels

  expect_error(is_connected(g1,1,3))
  expect_error(is_connected(g1,"A",3))
  expect_error(is_connected(g1,1,"C"))
  expect_error(is_connected(g1,"A","C"))

  expect_error(is_connected(g1,1,TRUE))
  expect_error(is_connected(g1,"A",TRUE))

  expect_error(is_connected(g1,1,NaN))
  expect_error(is_connected(g1,"A",NaN))

  expect_error(is_connected(g1,1,NA_real_))
  expect_error(is_connected(g1,"A",NA_real_))
  expect_error(is_connected(g1,1,NA_integer_))
  expect_error(is_connected(g1,"A",NA_integer_))
  expect_error(is_connected(g1,1,NA_character_))
  expect_error(is_connected(g1,"A",NA_character_))
  expect_error(is_connected(g1,1,NA_complex_))
  expect_error(is_connected(g1,"A",NA_complex_))

#bad graphs
 bad_g1 = list(list())
  bad_g2 = list(list(edges = 1L))
  bad_g3 = list(list(weights = 1))

  expect_error(is_connected(bad_g1,1,1))
  expect_error(is_connected(bad_g2,1,1))
  expect_error(is_connected(bad_g3,1,1))

  expect_error(is_connected(1,1,1))
  expect_error(is_connected(1L,1,1))
  expect_error(is_connected("1",1,1))
  expect_error(is_connected(TRUE,1,1))


```

