---
title: "Write up"
author: "Sophie Lee"
date: "September 17, 2014"
output: html_document
---

The graph we generated summarizes the information of the goals by the players of the final four countries: Germany (champion), Argentina (runner up), Netherlands (third place), and Brazil (fourth place). Represented by its own flag, each country graph shows the range of goals and the time (in minutes) that the goal was scored, as well as the name of the goaler. As the champion, Germany made the most goals among the four countries. In contrast, Argentina has made its way up as a good defensive team. In terms of the style in aggression, Germany scored many of its goals early on while the Netherlands scored many of its goals later towards the end of the second half.    

Minjung's part

In this data set, we are trying to look at the pattern of goals in terms of time and distance. 
We believe that we can figure out each team’s strengths and weaknesses by comparing the pattern of goal distances by time. 
In order to make an interesting interpretation, we only focus on four teams in World Cup 2014 semi finals; Germany, Argentina, Netherland and Brazil. 
As we can see, in the upper left part of our visualization, Germany scores the most goals. 
Relatively, most of goals were made in the first half of the game and in medium long-distance.
In the upper right part, Argentina scores the least goals. Most of goals were made in long-distance, which might represent there are players who do well in long-distance. 
In the lower left part, Netherland made most of their goals in the second half of the game. We can guess they are usually doing better in the second half, which could be their strengths. 
In the lower right part, Brazil made their goals in various distance and time. 
We can guess that there are many players who are good at short distance, medium-long distance or long distance.


```{r}

```

