---
  title: "Denny's"
author: "Sophie Lee"
date: "9/30/2014"
output: html_document
---
  This is my attempt!
  
```{r}

## load required packages

check_packages = function(names)
{
  for(name in names)
  {
    if (!(name %in% installed.packages()))
      install.packages(name, repos="http://cran.us.r-project.org")
    
    library(name, character.only=TRUE)
  }
}

check_packages(c("httr","XML","stringr","jsonlite","rgeos","maptools", "rgdal","ggplot2","utils","jsonlite","sp"))




### download the US map file 
## or you can mannually download the file from the following url and save it in your working directory.

temp<-tempfile()
download.file("http://www.arcgis.com/sharing/rest/content/items/f7f805eb65eb4ab787a0a3e1116ca7e5/data", temp)
unzip(temp)

####

us = readShapeSpatial("states") #this function requires maptools
c1=rep(1:length(us$STATE_NAME))==which(us$STATE_NAME=="Hawaii")
c2=rep(1:length(us$STATE_NAME))==which(us$STATE_NAME=="Alaska")
cs=cbind(c1,c2)
main=which(cs[,1]==FALSE & cs[,2]==FALSE)
mainland<-us[main,]
rm(c1)
rm(c2)
rm(cs)

### plotting the mainland  
plot(mainland)

### Plot the centers of each state

state.center=coordinates(gCentroid(us, byid=TRUE)) #coordinates require sp package, gCentroid function requires rgeos package (rgeos -not avaialbe for Maverick yet)
state.center=as.data.frame(state.center)
rownames(state.center)=as.character(mainland$STATE_NAME)
plot(state.center)

## plot the mainland with state centers
plot(mainland)
points(state.center, pch=19, cex=0.3)
states_abbr=as.data.frame(mainland$STATE_ABBR)
states_name=as.data.frame(mainland$STATE_NAME)


key="8D6F0428-F3A9-11DD-8BF2-659237ABAA09"  
  


for(i in 1:nrow(county_loc))
  {
    name = states[i]
    lat  = state.center[i,2]
    long = state.center[i,1]
    
     offset = 0
     j = 1
    
    repeat 
    {
      cat("Fetching", name, "- Page",j,"...\n")   #Fetchinig requires jsonlite
      
      url = paste0("http://hosted.where2getit.com/dennys/ajax?&xml_request=%3Crequest%3E%3Cappkey%3E",
        key,
        "%3C%2Fappkey%3E%3Cformdata+id%3D%22locatorsearch%22%3E%3Cdataview%3Estore_default%3C%2Fdataview%3E%3Climit%3E3000%3C%2Flimit%3E%3Cgeolocs%3E%3Cgeoloc%3E%3Caddressline%3E,%20",
        county_loc[i],
        "%3C%2Faddressline%3E%3Clongitude%3E%3C%2Flongitude%3E%3Clatitude%3E%3C%2Flatitude%3E%3C%2Fgeoloc%3E%3C%2Fgeolocs%3E%3Csearchradius%3E3000|10000%3C%2Fsearchradius%3E%3C%2Fformdata%3E%3C%2Frequest%3E")   


      
      d=GET(url)
      
      stopifnot(d$status_code == 200)
      
      # Clean up jQuery wrapper to get valid json
      s = content(d, as="text")
#       s = str_replace(s, "[a-zA-Z0-9_]+\\(", "")
#       s = str_replace(s, "}\\)","}")
      
      # Save the file locally
      file = paste0("json/",name,"_",j,".json")
      write(s, file=file)
      
      json = fromJSON(s)
      
      if (json$paging$total <= offset+50)
        break
      
      offset = offset+50
      j = j+1
    }
    
    # Wait a bit before moving on to the next county
    Sys.sleep(rexp(1,1/5))
  }




  
  
  
  
  

```


```{r, echo=FALSE}




```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

